name: Validate

on:
  pull_request:
  push:

jobs:
  validate:
    name: Validating Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Check types and Build
        run: yarn tsc --noEmit && NODE_ENV=PRODUCTION yarn run build
      - name: Pack Chrome Extension
        run: yarn run extension:pack
      - name: Upload Userscript And Extension
        uses: actions/upload-artifact@v3
        with:
          name: Userscript and Unpacked Extension
          path: |
            dist/eureka-loader.user.js
            dist/unpacked-extension.zip
